//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftWorkDetail
    {
        public int Id { get; set; }
        public Nullable<int> ShiftWorkID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual ShiftWork ShiftWork { get; set; }
        public virtual User User { get; set; }
    }
}
