//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMng.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpendingMoney
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public decimal TotalPrice { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
    }
}
